name: Build and Release macOS

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: macos-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build application with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller ADbenQ.spec

      - name: Move executable
        run: |
          mv dist/ADBenQ ADBenQ

      - name: Create tarball
        run: |
          tar -czvf ADbenQ_macos.tar.gz ADBenQ

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ADBenQ
          path: ./ADBenQ_macos.tar.gz

  create_release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ADBenQ

      - name: Create draft release
        uses: softprops/action-gh-release@v1
        with:
          files: ADBenQ_macos.tar.gz
          draft: true
