name: Build DMG

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build the application
    - name: Build the application
      run: |
        ./build.sh

    # Create DMG
    - name: Create DMG
      run: |
        mkdir -p dist/dmg
        hdiutil create dist/dmg/ADBenQ.dmg -srcfolder dist/macos/ADBenQ -ov -format UDZO

    # Upload DMG as an artifact
    - name: Upload DMG
      uses: actions/upload-artifact@v3
      with:
        name: ADBenQ.dmg
        path: dist/dmg/ADBenQ.dmg
