name: Build macOS Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS executable with PyInstaller
        run: |
          chmod +x build.sh
          ./build.sh
        shell: bash

      - name: Verify build artifacts
        run: |
          if [ ! -f "dist/macos/ADBenQ/ADBenQ" ]; then
            echo "Build failed: Executable not found!"
            exit 1
          fi

      - name: Archive the executable
        run: |
          mv dist/macos/ADBenQ/ADBenQ /tmp/ADBenQ
          tar -czf adbenq_macos_arm.tar.gz -C /tmp ADBenQ

      - name: Get latest GitHub release tag
        id: get_latest_tag
        run: echo ::set-output name=tag::$(git describe --tags --abbrev=0)

      - name: Append macOS executable to latest GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: adbenq_macos_arm.tar.gz
          tag_name: ${{ steps.get_latest_tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
